# Pandas Cleaning

Load in the data.

In [1]:
# Install datasets Library (if not already installed)
# !pip install -U datasets

# Importing Libraries
import pandas as pd
from datasets import load_dataset

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

## Date and Time

### Datetime

#### Notes

* `pd.to_datetime()`: Convert argument to datetime.

#### Example

In our DataFrame the `job_posted_date` is actually a string not a datetime format. First let's convert it to datetime format. 

We'll also use `info()` to check if the data type changed from a string to a `datetime` format.

In [3]:
# Convert 'job_posted_date' to datetime without specifying the exact format

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'],errors = 'coerce')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

### Date

#### Notes

* `dt`: accessor that provides a way to access specialized methods and properties we use to work with datatime data within a pandas series. 
* `date`: extract the date component from the datetime object in the series. 
* Use together `dt.date` on our series.

#### Example

Now let's turn it from a datetime to a date using `dt.date`.

In [ ]:
df['job_posted_date'] = df['job_posted_date'].dt.date

df.head()

AttributeError: Can only use .dt accessor with datetimelike values

#### Note: For the rest of the time we're loading the data in we'll be automatically turn the `job_posted_date` column into a datetime object.

## Sorting Values

### Notes

* `sort_values()` sorts a DataFrame or a specific column in ascending or descending order based on one or more columns. 
* Typically this is used to sort by a specific column/s.
* Parameters: 
    * `by` - column name or list of column names to sort by
    * `ascending` - boolean or list of booleans, default `True`, to sort by descending you would use `False`
    * `inplace` - whether to modify the DataFrame in place or return a new one

### Example

Let's sort our DataFrame by the `job_posted_date` in descending order (from most recent date to least).

In [10]:
df.sort_values(by='job_posted_date',ascending = False, inplace =True)

df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
287457,Senior Data Engineer,Senior Data Engineer,"Randburg, South Africa",via CareerJunction,Full-time,False,South Africa,2023-12-31,False,False,South Africa,None,NaN,NaN,DCV Sabenza IT and Recruitment,"['sql', 'python', 'databricks', 'azure', 'hado...","{'analyst_tools': ['ssrs', 'power bi', 'tablea..."
646083,Data Scientist,DATA SCIENTIST regio Utrecht – PHARMO Institut...,"Nieuwegein, Netherlands",via Utrecht.work,Full-time,False,Netherlands,2023-12-31,False,False,Netherlands,None,NaN,NaN,Nationale Vacaturebank,None,None
114666,Senior Data Engineer,Senior Data Engineer (Python),"Wichita Falls, TX",via LinkedIn,Full-time and Part-time,False,Georgia,2023-12-31,False,True,United States,None,NaN,NaN,ClickJobs.io,"['python', 'java', 'scala', 'nosql', 'sql', 'm...","{'cloud': ['redshift', 'snowflake', 'aws', 'az..."
696752,Data Engineer,Senior Data Engineer II,"Orange, CA",via BeBee,Full-time,False,Sudan,2023-12-31,False,True,Sudan,None,NaN,NaN,MobilityWare,"['python', 'java', 'c#', 'sql', 'aws', 'snowfl...","{'cloud': ['aws', 'snowflake', 'gcp'], 'librar..."
83884,Software Engineer,SAP B1 Applications Analyst,Germany,via BeBee,Full-time,False,Germany,2023-12-31,True,False,Germany,None,NaN,NaN,Systems Accountants,"['sql', 'crystal', 'sap']","{'analyst_tools': ['sap'], 'programming': ['sq..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
542527,Data Scientist,Data Science Consultant,"Taguig, Metro Manila, Philippines",via Trabajo.org,Full-time,False,Philippines,2023-01-01,False,False,Philippines,None,NaN,NaN,AIA,None,None
137492,Data Engineer,Data Engineer - Customer Insights,"Amsterdam, Netherlands",via Melga,Full-time,False,Netherlands,2023-01-01,False,False,Netherlands,None,NaN,NaN,Booking.com,"['java', 'scala', 'python', 'perl', 'sql', 'my...","{'databases': ['mysql', 'cassandra'], 'librari..."
778984,Cloud Engineer,Configuration Management Analyst,"Dublin, Ireland",via Trabajo.org,Full-time,False,Ireland,2023-01-01,True,False,Ireland,None,NaN,NaN,Vantage Resources,None,None
707242,Software Engineer,Software Engineer,Finland,via Trabajo.org,Full-time,False,Finland,2023-01-01,False,False,Finland,None,NaN,NaN,Uber,"['c++', 'nosql', 'python', 'java', 'go', 'kafka']","{'libraries': ['kafka'], 'programming': ['c++'..."
347766,Data Engineer,"Manager, Data Engineering, SMAI","Bengaluru, Karnataka, India",via Careers At Micron Technology,Full-time,False,India,2023-01-01,False,False,India,None,NaN,NaN,Micron Technology,"['python', 'snowflake', 'gcp', 'hadoop']","{'cloud': ['snowflake', 'gcp'], 'libraries': [..."

## Adding a Column

### Notes

- If you want to create a column you'll need to use the `df['column_name']` syntax.

### Example

Here we are creating a new column called 'Is Data Analyst' and saying if the column `job_title_short` is equal to 'Data Analyst' then then return 1 if not, return 0. It does this by using `astype(int)`.

In [12]:
df['Is Data Analyst'] = (df['job_title_short'] == 'Data Analyst').astype(int)

Let's view this new column we created.

In [13]:
df['Is Data Analyst']

287457    0
646083    0
114666    0
696752    0
83884     0
         ..
542527    0
137492    0
778984    0
707242    0
347766    0
Name: Is Data Analyst, Length: 785741, dtype: int64

Did this work? Let's look at cases when this column is greater than 0, which means it is equal to 1 (aka it's true). We can use our row filtering we learned in the last section.

In [14]:
df[df['Is Data Analyst'] > 0]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,Is Data Analyst
696478,Data Analyst,Working Student for Voice Assistant Data Annot...,"Berlin, Germany",via XING,Full-time,False,Germany,2023-12-31,False,False,Germany,None,NaN,NaN,MBition GmbH,None,None,1
83980,Data Analyst,Data analyst,"Dallas, TX",via Talent.com,Full-time,False,"Texas, United States",2023-12-31,True,False,United States,None,NaN,NaN,Motion Recruitment,"['sql', 'azure', 'dax']","{'analyst_tools': ['dax'], 'cloud': ['azure'],...",1
621709,Data Analyst,Business Intelligence Engineer,Greece,via Trabajo.org,Full-time,False,Greece,2023-12-31,True,False,Greece,None,NaN,NaN,Randstad Hellas,"['sql', 'ssis']","{'analyst_tools': ['ssis'], 'programming': ['s...",1
237132,Data Analyst,Data Analyst,"New York, NY",via ZipRecruiter,Full-time,False,"New York, United States",2023-12-31,False,False,United States,None,NaN,NaN,Columbia University,['r'],{'programming': ['r']},1
397120,Data Analyst,Data Analyst,Singapore,via BeBee Singapore,Internship,False,Singapore,2023-12-31,True,False,Singapore,None,NaN,NaN,Howden Singapore Pte Ltd,"['outlook', 'excel', 'powerpoint', 'sharepoint']","{'analyst_tools': ['outlook', 'excel', 'powerp...",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
443420,Data Analyst,Commercial Data Analyst,"Nicosia, Cyprus",via BeBee Cyprus,Full-time,False,Cyprus,2023-01-01,False,False,Cyprus,None,NaN,NaN,GRS Recruitment,"['sql', 'excel']","{'analyst_tools': ['excel'], 'programming': ['...",1
220561,Data Analyst,JUNIOR/GRADUATE DATA ANALYST – DEBT AND COLLEC...,"Nottingham, UK",via LinkedIn,Full-time,False,United Kingdom,2023-01-01,True,False,United Kingdom,None,NaN,NaN,Harnham,"['sql', 'excel']","{'analyst_tools': ['excel'], 'programming': ['...",1
341561,Data Analyst,GCP Data Analyst,"Frisco, TX",via LinkedIn,Contractor,False,"Texas, United States",2023-01-01,False,False,United States,None,NaN,NaN,Micasa Global,"['sql', 'shell', 'gcp', 'bigquery', 'node', 'k...","{'cloud': ['gcp', 'bigquery'], 'other': ['kube...",1
220269,Data Analyst,Jr Data Analyst,"Atlanta, GA",via LinkedIn,Contractor,False,Georgia,2023-01-01,False,False,United States,None,NaN,NaN,"RIT Solutions, Inc.","['go', 'sql', 'word', 'tableau', 'excel', 'flo...","{'analyst_tools': ['word', 'tableau', 'excel']...",1
57877,Data Analyst,Data Analyst Dubai,Dubai - United Arab Emirates,via Indeed,Full-time,False,United Arab Emirates,2023-01-01,True,False,United Arab Emirates,None,NaN,NaN,Jobleads-AE/BR/HK/MX/ZA,['sql'],{'programming': ['sql']},1

## Dropping Data

### Notes

* Use `drop()` if you want to drop (delete) either a column or row in your database. 
* The syntax is:
    * Drop column: `df.drop('column_name, axis = 1)`
    * Drop row: `df.drop(index_name, axis = 0)`
* If you wanted to drop multiple rows you would have the syntax: 
    * Drop multiple columns: `df.drop(['column_name1', 'column_name2'], axis=1)`
    * Drop multiple rows: `df.drop([index_name1, index_name2], axis=0)`

### Examples

Let's drop the column `'salary_hour_avg'`, this will have an axis of 1 (since we're dropping a column).

In [17]:
df.drop('salary_hour_avg',axis= 1, inplace = True)

Inspecting the columns available now:

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 785741 entries, 287457 to 347766
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  company_name           785723 non-null  object
 14  job_skills             668704 non-null  object
 15  job_type_skills        668704 non-null  object
 16  Is Data Analyst        785741 non-null  int64
dtypes: bool(3), float64(1), int64(1), object(12)
memory usage: 92.2+ MB

This column is now removed!

## Remove NA

### Notes

* To remove rows that contain empty cells use `dropna()`. 
* By default `dropna()` will return a *new* DataFrame, and won't change the original. 

### Example

Let's cleanup our `salary_year_avg` column by removing the `NaN` values in this column.

In [ ]:
df.salary_year_avg.head()

In [19]:
df.dropna(subset='salary_year_avg',inplace = True)

In [20]:
df.salary_year_avg.head()

574802     95150.0
120858    144000.0
122037    137500.0
3448      140000.0
581356    135000.0
Name: salary_year_avg, dtype: float64