## apply() - Calaculate Projected Salary Next Year

In [1]:
#Importing Libraries
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset

#Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df=dataset['train'].to_pandas()

#Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

c:\Users\ELCOT\anaconda3\envs\python_course\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [5]:
df.iloc[28]

job_title_short                                             Data Scientist
job_title                                              CRM Data Specialist
job_location                       San José Province, San José, Costa Rica
job_via                                                    via Ai-Jobs.net
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                                 Costa Rica
job_posted_date                                        2023-08-01 13:37:57
job_no_degree_mention                                                False
job_health_insurance                                                 False
job_country                                                     Costa Rica
salary_rate                                                           year
salary_year_avg                                                   109500.0
salary_hour_avg                                                        NaN
company_name                                                      Netskope
job_skills                                               ['gdpr', 'excel']
job_type_skills          {'analyst_tools': ['excel'], 'libraries': ['gd...
Name: 28, dtype: object

In [2]:
df.loc[df['salary_year_avg'].notna(), 'salary_year_avg']

28        109500.0
77        140000.0
92        120000.0
100       228222.0
109        89000.0
            ...
785624    139216.0
785641    150000.0
785648    221875.0
785682    157500.0
785692    157500.0
Name: salary_year_avg, Length: 22003, dtype: float64

In [ ]:
def projected_salary(salary):
    return salary * 1.03

df_salary = df.loc[df['salary_year_avg'].notna(),['salary_year_avg']].copy()

df_salary['salary_year_inflated'] = df_salary.apply(projected_salary)

In [45]:
df_salary

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [55]:
df_salary = df.loc[df['salary_year_avg'].notna(),['salary_year_avg','salary_hour_avg']].copy()
df_salary[['salary_year_inflated','salary_hour_inflated']]= df_salary.apply(lambda salary: salary * 1.03)
df_salary

,salary_year_avg,salary_hour_avg,salary_year_inflated,salary_hour_inflated
28,109500.0,NaN,112785.00,NaN
77,140000.0,NaN,144200.00,NaN
92,120000.0,NaN,123600.00,NaN
100,228222.0,NaN,235068.66,NaN
109,89000.0,NaN,91670.00,NaN
...,...,...,...,...
785624,139216.0,NaN,143392.48,NaN
785641,150000.0,NaN,154500.00,NaN
785648,221875.0,NaN,228531.25,NaN
785682,157500.0,NaN,162225.00,NaN
785692,157500.0,NaN,162225.00,NaN

In [57]:
df_salary = df.loc[df['salary_year_avg'].notna(),['salary_year_avg','salary_hour_avg']].copy()
df_salary[['salary_year_inflated','salary_hour_inflated']] = df_salary* 1.03
df_salary

,salary_year_avg,salary_hour_avg,salary_year_inflated,salary_hour_inflated
28,109500.0,NaN,112785.00,NaN
77,140000.0,NaN,144200.00,NaN
92,120000.0,NaN,123600.00,NaN
100,228222.0,NaN,235068.66,NaN
109,89000.0,NaN,91670.00,NaN
...,...,...,...,...
785624,139216.0,NaN,143392.48,NaN
785641,150000.0,NaN,154500.00,NaN
785648,221875.0,NaN,228531.25,NaN
785682,157500.0,NaN,162225.00,NaN
785692,157500.0,NaN,162225.00,NaN

In [65]:
import ast
def cleanlist(skill):
    if pd.notna(skill):
     return ast.literal_eval(skill)
df['job_skills'] = df['job_skills'].apply(cleanlist)

In [73]:
type(df['job_skills'][1])

list

In [101]:
def projected_salary(salary):
    if 'senior' in df['job_title_short']:
        return salary * 1.5
    else:
        return salary * 1.3

df_salary = df[['job_title_short','salary_year_avg']].copy()

df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(projected_salary)
df_salary[~df_salary['job_title_short'].str.contains('Senior', na=False)]

          job_title_short  salary_year_avg  salary_year_inflated
1            Data Analyst              NaN                   NaN
2           Data Engineer              NaN                   NaN
3           Data Engineer              NaN                   NaN
4           Data Engineer              NaN                   NaN
5           Data Engineer              NaN                   NaN
...                   ...              ...                   ...
785736  Software Engineer              NaN                   NaN
785737       Data Analyst              NaN                   NaN
785738   Business Analyst              NaN                   NaN
785739      Data Engineer              NaN                   NaN
785740  Software Engineer              NaN                   NaN

[675005 rows x 3 columns]

In [84]:
df_salary.loc[df['salary_year_avg'].notna()]

       job_title_short  salary_year_avg  salary_year_inflated
28      Data Scientist         109500.0              142350.0
77       Data Engineer         140000.0              182000.0
92       Data Engineer         120000.0              156000.0
100     Data Scientist         228222.0              296688.6
109       Data Analyst          89000.0              115700.0
...                ...              ...                   ...
785624   Data Engineer         139216.0              180980.8
785641   Data Engineer         150000.0              195000.0
785648  Data Scientist         221875.0              288437.5
785682  Data Scientist         157500.0              204750.0
785692  Data Scientist         157500.0              204750.0

[22003 rows x 3 columns]

In [99]:
def projected_salary(row):
    if 'senior' in row['job_title_short']:
        return row['salary_year_avg'] * 1.5
    else:
        return  row['salary_year_avg'] * 1.3

df_salary = df.loc[df['salary_year_avg'].notna(),['job_title_short','salary_year_avg']].copy()

df_salary['salary_year_inflated'] = df_salary.apply(projected_salary,axis=1)
df_salary[df_salary['job_title_short'].str.contains('Senior', na=False)]

              job_title_short  salary_year_avg  salary_year_inflated
495      Senior Data Engineer         168500.0             219050.00
573      Senior Data Engineer         160000.0             208000.00
657      Senior Data Engineer         165000.0             214500.00
726      Senior Data Engineer         173500.0             225550.00
733      Senior Data Engineer         160000.0             208000.00
...                       ...              ...                   ...
784947   Senior Data Engineer         150000.0             195000.00
785106   Senior Data Engineer         125000.0             162500.00
785132  Senior Data Scientist          99150.0             128895.00
785330  Senior Data Scientist         200935.5             261216.15
785340  Senior Data Scientist         196800.0             255840.00

[4412 rows x 3 columns]

In [98]:
df_salary

       job_title_short  salary_year_avg  salary_year_inflated
28      Data Scientist         109500.0              142350.0
77       Data Engineer         140000.0              182000.0
92       Data Engineer         120000.0              156000.0
100     Data Scientist         228222.0              296688.6
109       Data Analyst          89000.0              115700.0
...                ...              ...                   ...
785624   Data Engineer         139216.0              180980.8
785641   Data Engineer         150000.0              195000.0
785648  Data Scientist         221875.0              288437.5
785682  Data Scientist         157500.0              204750.0
785692  Data Scientist         157500.0              204750.0

[22003 rows x 3 columns]

In [103]:
list=['senior','data','analyst']
if 'senior' in list:
    print(list)

['senior', 'data', 'analyst']